# Generated by Django 5.2.4 on 2025-07-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bano', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=100)),
                ('maketype', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('modelyear', models.PositiveIntegerField()),
                ('civil_reg_no', models.CharField(max_length=100)),
                ('entry_datetime', models.DateTimeField(blank=True, null=True)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('nomenclature', models.CharField(max_length=100)),
                ('entry_milometer', models.PositiveIntegerField()),
                ('exit_milometer', models.PositiveIntegerField()),
                ('entry_fuel', models.PositiveIntegerField()),
                ('exit_fuel', models.PositiveIntegerField()),
                ('driver', models.CharField(max_length=100)),
                ('driver_contact', models.PositiveIntegerField()),
                ('officer', models.CharField(max_length=100)),
                ('officer_rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in', 'In'), ('in_process', 'In Process'), ('out', 'Out')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
