# Generated by Django 5.2.4 on 2025-07-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='entry_fuel',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='entry_milometer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='exit_fuel',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='exit_milometer',
        ),
    ]
