# Generated by Django 5.2.4 on 2025-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('nomenclature', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='spare_parts/')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractor', models.CharField(max_length=100)),
                ('make_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
