# Generated by Django 5.2.4 on 2025-07-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='origin',
            field=models.CharField(default='Imported', max_length=100),
        ),
    ]
