# Generated by Django 5.2.4 on 2025-07-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpareParts', '0002_sparepart_origin'),
        ('Vehicles', '0002_remove_vehicle_entry_fuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepart')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle')),
            ],
        ),
    ]
