# Generated by Django 5.2.4 on 2025-07-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehicles', '0002_remove_vehicle_entry_fuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trade', models.CharField(max_length=100)),
                ('skill_lvl', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('left_date', models.DateField(blank=True, null=True)),
                ('svc_yrs', models.PositiveIntegerField(default=0, editable=False)),
                ('meno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mechanics.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_description', models.TextField()),
                ('date', models.DateField()),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('history_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vehicles.vehiclehistory')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mechanics.mechanic')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle')),
            ],
        ),
    ]
