# Generated by Django 5.2.4 on 2025-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='meno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
